repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # fixing config files
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [ --autofix,--indent=2,--no-ensure-ascii,--no-sort-keys, ]
      # fixing source files
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      # git helper
      - id: check-merge-conflict
      # credential checker
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]

  # notebook strip output
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [ cython ]
      - id: isort
        name: isort (pyi)
        types: [ pyi ]

  # dockerfile linter
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
      # todo: when setup.py is setup for dev purposes, it should install hadolint
      # then, one could use `id: hadolint` without the need for docker to be installed

  # python formatter
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  # python linter
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
