version: "3.9"
services:

  btc_prediction_repo:
    image: btc_prediction_repo
    build: .
    network_mode: "host"
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
